prevent_proxy_connections: false
listeners:
- query_port: 25595
  motd: test
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 30
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
log_pings: true
connection_throttle_limit: 2
server_connect_timeout: 5000
timeout: 30000
player_limit: 100
ip_forward: true
groups:
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 95018f7d-ef52-4385-a977-61e7cef439f8
online_mode: true
forge_support: false
disabled_commands:
- bungee
- perms
servers:
  lobby:
    motd: |-
      &8>&7> &fMiniCraft &7<&8< &aMinigames Netzwerk&r
      &c[&b1.16.x&c][&bEntwicklungsphase&c]
    address: 127.0.0.1:25566
    restricted: false
  ffa:
    motd: FFA
    address: 127.0.0.1:25568
    restricted: false
  gtc-01:
    motd: GTC
    address: 127.0.0.1:25569
    restricted: false
  gtc-02:
    motd: GTC
    address: 127.0.0.1:25570
    restricted: false
