prevent_proxy_connections: false
listeners:
- query_port: 25577
  motd: test
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 100
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: null
  DuWirstNiemalsDieseRechteBesitzen:
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: 100
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 95018f7d-ef52-4385-a977-61e7cef439f8
online_mode: true
forge_support: false
disabled_commands:
- bungee
- perms
servers:
  lobby:
    motd: |-
      &8>&7> &fMiniCraft &7<&8< &aMinigames Netzwerk&r
      &c[&b1.16.x&c][&bEntwicklungsphase&c]
    address: localhost:25566
    restricted: false
  FFA:
    motd: '&1Just another Waterfall - Forced Host'
    address: localhost:25567
    restricted: false
  GTC:
    motd: GTC
    address: localhost:25568
    restricted: false
