(cd /home/MiniCraft/BungeeServer/Waterfall; ./start.sh)
(cd /home/MiniCraft/BungeeServer/Lobby/SERVER-1; ./start.sh)
(cd /home/MiniCraft/BungeeServer/Lobby/SERVER-2; ./start.sh)
(cd /home/MiniCraft/BungeeServer/GTC/SERVER-1; ./start.sh)
(cd /home/MiniCraft/BungeeServer/GTC/SERVER-2; ./start.sh)
(cd /home/MiniCraft/BungeeServer/FFA; ./start.sh)